[build]
  base = "frontend"
  publish = "dist"
  command = """
    npm install -g vite
    npm ci
    npm run build
  """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"