[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["../backend/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200