services:
  - type: web
    name: disaster-app
    env: node # or static, depending on whether you need Node.js at runtime
    buildCommand: |
      cd frontend
      npm install
      npm install -g vite
      npm run build
    startCommand: |
      cd frontend
      npm install -g serve
      serve -s dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://disaster-app.onrender.com