services:
  - type: web
    name: disaster-app-backend
    env: node
    buildCommand: npm ci --force && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      # Add other environment variables as needed

  - type: web
    name: disaster-app-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm install -g serve
      serve -s dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://disaster-app.onrender.com